https://www.fao.org/faostat/en/#data/RFN

Fertilizers by Nutrient

In [ ]:
# %pip install pandas matplotlib seaborn

In [2]:
import pandas as pd

df = pd.read_csv("Inputs_FertilizersNutrient_E_All_Data/Inputs_FertilizersNutrient_E_All_Data_NOFLAG.csv")
df.head()

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y1961,Y1962,...,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Y2021,Y2022,Y2023,Y2024
0,2,'004,Afghanistan,3102,Nutrient nitrogen N (total),5510,Production,t,NaN,NaN,...,14416.0,14416.00,14416.0,14416.00,14416.00,14416.00,14416.00,14416.00,14416.0,14416.00
1,2,'004,Afghanistan,3102,Nutrient nitrogen N (total),5610,Import quantity,t,1000.00,1000.00,...,78230.0,82434.00,177397.0,106194.00,167962.00,141441.00,34676.00,37236.00,24419.0,87001.00
2,2,'004,Afghanistan,3102,Nutrient nitrogen N (total),5910,Export quantity,t,NaN,NaN,...,0.0,22.00,5.0,0.00,22.00,0.00,117.00,769.00,3107.0,0.00
3,2,'004,Afghanistan,3102,Nutrient nitrogen N (total),5157,Agricultural Use,t,1000.00,1000.00,...,92515.0,96670.00,140775.0,120609.00,59692.00,43141.00,33341.00,26035.00,35722.0,101417.00
4,2,'004,Afghanistan,3102,Nutrient nitrogen N (total),5159,Use per area of cropland,kg/ha,0.13,0.13,...,11.7,12.22,17.8,15.06,7.45,5.34,4.12,3.22,4.4,12.55

In [3]:
# Show the frequency distribution of the "Item" column
df["Item"].value_counts()

Item
Nutrient nitrogen N (total)        1763
Nutrient phosphate P2O5 (total)    1763
Nutrient potash K2O (total)        1758
Name: count, dtype: int64

In [17]:
df.loc[df["Area"] == "Belgium", ["Item", "Element Code", "Element", "Y2019"]]

,Item,Element Code,Element,Y2019
332,Nutrient nitrogen N (total),5510,Production,968138.00
333,Nutrient nitrogen N (total),5610,Import quantity,568088.00
334,Nutrient nitrogen N (total),5910,Export quantity,1225446.00
335,Nutrient nitrogen N (total),5157,Agricultural Use,153353.00
336,Nutrient nitrogen N (total),5159,Use per area of cropland,174.08
337,Nutrient nitrogen N (total),5172,Use per capita,13.35
338,Nutrient nitrogen N (total),5173,Use per value of agricultural production,16.71
339,Nutrient phosphate P2O5 (total),5510,Production,269729.00
340,Nutrient phosphate P2O5 (total),5610,Import quantity,125379.00
341,Nutrient phosphate P2O5 (total),5910,Export quantity,367997.00
342,Nutrient phosphate P2O5 (total),5157,Agricultural Use,13373.00
343,Nutrient phosphate P2O5 (total),5159,Use per area of cropland,15.18
344,Nutrient phosphate P2O5 (total),5172,Use per capita,1.16
345,Nutrient phosphate P2O5 (total),5173,Use per value of agricultural production,1.46
346,Nutrient potash K2O (total),5510,Production,0.00
347,Nutrient potash K2O (total),5610,Import quantity,825768.00
348,Nutrient potash K2O (total),5910,Export quantity,356155.00
349,Nutrient potash K2O (total),5157,Agricultural Use,61212.00
350,Nutrient potash K2O (total),5159,Use per area of cropland,69.48
351,Nutrient potash K2O (total),5172,Use per capita,5.33
352,Nutrient potash K2O (total),5173,Use per value of agricultural production,6.67

In [ ]:
year_cols = [y for y in df.columns if y[0] == "Y"]
year_cols

In [8]:
df_long = df.melt(
    id_vars=['Area', 'Item'], # Keep Country and Item fixed
    value_vars=year_cols,
    var_name='Year',
    value_name='Value'
)

# Clean up year strings ('Y1961' -> 1961)
df_long['Year'] = df_long['Year'].str.replace('Y', '').astype(int)

# Group by Country & Year to get non-null counts
counts_df = (
    df_long.dropna(subset=['Value'])
    .groupby(['Area', 'Year'])
    .size()
    .reset_index(name='non_null_count')
)

counts_df.head()

          Area  Year  non_null_count
0  Afghanistan  1961              13
1  Afghanistan  1962              13
2  Afghanistan  1963              13
3  Afghanistan  1964              13
4  Afghanistan  1965              13

In [13]:
with pd.option_context("display.max_rows", None):
    display(counts_df.loc[counts_df["Area"] == "Belgium"])

         Area  Year  non_null_count
1269  Belgium  2000               6
1270  Belgium  2001               6
1271  Belgium  2002              21
1272  Belgium  2003              21
1273  Belgium  2004              21
1274  Belgium  2005              21
1275  Belgium  2006              21
1276  Belgium  2007              21
1277  Belgium  2008              21
1278  Belgium  2009              21
1279  Belgium  2010              21
1280  Belgium  2011              21
1281  Belgium  2012              21
1282  Belgium  2013              21
1283  Belgium  2014              21
1284  Belgium  2015              21
1285  Belgium  2016              21
1286  Belgium  2017              21
1287  Belgium  2018              21
1288  Belgium  2019              21
1289  Belgium  2020              21
1290  Belgium  2021              21
1291  Belgium  2022              21
1292  Belgium  2023              21
1293  Belgium  2024              21