In [ ]:
# %pip install pyreadstat

In [3]:
import pandas as pd

df = pd.read_spss("UGA_R10.Data_22Apr24.wtd_.final_.release_updated.13Feb25.sav")
df.head()

,RESPNO,URBRUR,REGION_OLD,REGION,LOCATION.LEVEL.1,EA_SVC_A,EA_SVC_B,EA_SVC_C,EA_SVC_D,EA_SVC_E,...,Q115_4,Q115_5,Q115_6,Q115_7,Q115_8,Q115_9,Q115_10,Q115OTHER,withinwt_ea,withinwt_hh
0,UGA0001,Urban,Kampala,Kampala,KAMPALA,Yes,Yes,Can't determine,Yes,No,...,Lunyole,No further response,No further response,No further response,No further response,No further response,No further response,,0.577517,0.840025
1,UGA0002,Urban,Kampala,Kampala,KAMPALA,Yes,Yes,Can't determine,Yes,No,...,No further response,No further response,No further response,No further response,No further response,No further response,No further response,,0.577517,0.210006
2,UGA0003,Urban,Kampala,Kampala,KAMPALA,Yes,Yes,Can't determine,Yes,No,...,No further response,No further response,No further response,No further response,No further response,No further response,No further response,,0.577517,0.840025
3,UGA0004,Urban,Kampala,Kampala,KAMPALA,Yes,Yes,Yes,Yes,Yes,...,No further response,No further response,No further response,No further response,No further response,No further response,No further response,,0.922619,0.461309
4,UGA0005,Urban,Kampala,Kampala,KAMPALA,Yes,Yes,Yes,Yes,Yes,...,No further response,No further response,No further response,No further response,No further response,No further response,No further response,,0.922619,0.922619

In [5]:
print(*df.columns, sep=", ")

RESPNO, URBRUR, REGION_OLD, REGION, LOCATION.LEVEL.1, EA_SVC_A, EA_SVC_B, EA_SVC_C, EA_SVC_D, EA_SVC_E, EA_FAC_A, EA_FAC_B, EA_FAC_C, EA_FAC_D, EA_FAC_E, EA_FAC_F, EA_FAC_F2, EA_FAC_G, EA_SEC_A, EA_SEC_B, EA_SEC_C, EA_SEC_D, EA_SEC_E, EA_ROAD_A, EA_ROAD_B, EA_ROAD_C, NOCALL_1, NOCALL_2, NOCALL_3, NOCALL_4, NOCALL_5, NOCALL_6, NOCALL_7, NOCALL_8, DATEINTR, STRTIME, Q1, Q2, Q2OTHER, Q3, Q4A, Q4B, Q5A, Q5B, Q6, Q7A, Q7B, Q7C, Q7D, Q7E, Q8A, Q8B, Q8C, Q9, Q10A, Q10B, Q10C, Q11A, Q11B, Q11C, Q11D, Q12A, Q12B, Q12C, Q13A, Q13B, Q13C, Q13D, Q14, Q15, Q16A, Q16B, Q17, Q18A, Q18B, Q19, Q20, Q21A, Q21B, Q21C, Q22, Q23, Q24, Q25, Q26A, Q26B, Q27, Q28, Q29, Q30, Q31A, Q31B, Q31B_UGA, Q32, Q33, Q34A, Q34B, Q34C, Q34D, Q34E, Q34F, Q35, Q36A, Q36B, Q37A, Q37B, Q37C, Q37D, Q37E, Q37F, Q37G, Q37H, Q37I, Q37J, Q37K, Q37L, Q37M, Q37N_UGA, Q37O_UGA, Q37P_UGA, Q37Q_UGA, Q37R_UGA, Q37S_UGA, Q38A, Q38B, Q38C, Q38D, Q38E, Q38F, Q38G, Q38H, Q38I, Q38J, Q38K, Q39A, Q39B, Q40A, Q40B, Q40C, Q40D, Q40E, Q40F, Q40G, Q40H, Q41A, Q41B, Q41C, Q41D, Q42A, Q42B, Q42C_UGA, Q42D_UGA, Q42E_UGA, Q43, Q44A, Q44B, Q44C, Q45A, Q45B, Q45C, Q45D, Q45E, Q46PT1OTHER, Q46PT1, Q46PT2OTHER, Q46PT2, Q46PT3OTHER, Q46PT3, Q47A, Q47B, Q47C, Q47D, Q47E, Q47F, Q47G, Q47H, Q47I, Q47J, Q47K, Q47L, Q47M, Q48A, Q48B, Q48C, Q49A, Q49B, Q50, Q51, Q52A, Q52B, Q52C, Q52D, Q53A, Q53B, Q54, Q54Other, Q55A, Q55B, Q55C, Q55D, Q55E, Q56, Q57A, Q57B, Q58, Q59A, Q59B, Q59C, Q59D_UGA, Q59E_UGA, Q60A, Q60B, Q61A, Q61B, Q62A, Q62B, Q62C, Q62D, Q63A, Q63B, Q63C, Q63D, Q63E_UGA, Q63F_UGA, Q64A, Q64B, Q64C, Q64D, Q64E, Q65A, Q65B, Q65C, Q65D, Q65E, Q66, Q67A, Q67B, Q67C, Q67D, Q67E, Q67F, Q67G, Q67H, Q68, Q69A, Q69B, Q70A, Q70B, Q70C, Q71A, Q71B, Q72, Q72Other, Q73A, Q73B, Q73C, Q73D, Q74, Q75, Q76A, Q76B, Q77_UGA, Q78A_UGA, Q78B_UGA, Q78C_UGA, Q79A_UGA, Q79B_UGA, Q80A_UGA, Q80B_UGA, Q81A_UGA, Q81B_UGA, Q82, Q82Other, Q83A, Q83AOther, Q83B, Q83C, Q84, Q85A, Q85B, Q85C, Q85D, Q86A, Q86B, Q86C, Q86D, Q86E, Q86F, Q87A, Q87B, Q87C, Q87D, Q87E, Q88A, Q88B, Q88C, Q88D, Q88E, Q88F, Q89A, Q89B, Q89BOther, Q90A, Q90B, Q90C, Q90D, Q90E, Q90F, Q90G, Q90H, Q90I, Q90J, Q91A, Q91B, Q92, Q92Other, Q93A, Q93B, Q93C, Q93D, Q93DOther, Q94A, Q94B, Q94BOther, Q94C, Q94D, Q94E, Q95, Q96, Q97, Q97Other, Q98, Q98Other, Q99, Q99Other, Q100, ENDTIME, LENGTH, LENGTH_INT, Q101, Q102, Q102Other, Q103, Q104A, Q104B, Q104C, Q104D, Q104E, Q106A, Q106B, Q106C, Q106D, Q106E, Q106F, Q108, Q109, Q110, Q111, Q111OTHER, Q112, Q112OTHER, Q113, Q113OTHER, Q114, Q115_1, Q115_2, Q115_3, Q115_4, Q115_5, Q115_6, Q115_7, Q115_8, Q115_9, Q115_10, Q115OTHER, withinwt_ea, withinwt_hh

In [6]:
df = pd.read_csv("hdx_hapi_population_global_hrp.csv")
df.head()

C:\Users\Jochen\AppData\Local\Temp\ipykernel_25368\2098574265.py:1: DtypeWarning: Columns (19: warning, 20: error) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("hdx_hapi_population_global_hrp.csv")

,location_code,has_hrp,in_gho,provider_admin1_name,provider_admin2_name,admin1_code,admin1_name,admin2_code,admin2_name,admin_level,...,age_range,min_age,max_age,population,reference_period_start,reference_period_end,dataset_hdx_id,resource_hdx_id,warning,error
0,AFG,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,0,...,all,NaN,NaN,19844212,2021-01-01,2021-12-31,79484094-6e4a-4fbd-9152-66b42a9b32e0,73ec73cc-de29-4263-979e-4dbe6944820f,NaN,NaN
1,AFG,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,0,...,all,NaN,NaN,20567657,2021-01-01,2021-12-31,79484094-6e4a-4fbd-9152-66b42a9b32e0,73ec73cc-de29-4263-979e-4dbe6944820f,NaN,NaN
2,AFG,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,0,...,all,NaN,NaN,40411869,2021-01-01,2021-12-31,79484094-6e4a-4fbd-9152-66b42a9b32e0,73ec73cc-de29-4263-979e-4dbe6944820f,NaN,NaN
3,AFG,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0-4,0.0,4.0,3571135,2021-01-01,2021-12-31,79484094-6e4a-4fbd-9152-66b42a9b32e0,73ec73cc-de29-4263-979e-4dbe6944820f,NaN,NaN
4,AFG,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0-4,0.0,4.0,3707169,2021-01-01,2021-12-31,79484094-6e4a-4fbd-9152-66b42a9b32e0,73ec73cc-de29-4263-979e-4dbe6944820f,NaN,NaN